### ISSUE TITLE
Please stop blacklisting spamgourmet and other legitimate email domains.

### ISSUE THREAD

**Issue by foresto** [ivolo/disposable-email-domains#26]
This domain list is misguided and misleading at best. For example, spamgourmet and its alternative domains allow me to discover which web sites share my email address without my permission, which is one of the few effective defenses against spam. Like many users, I open every single message sent to my spamgourmet addresses unless the sender is has proven to be a spammer (this is exactly spamgourmet's purpose after all) which makes the apparent premise of this list just plain wrong.

Sadly, lists like this one have led some web sites to refuse signups to legitimate users, or worse yet, to silently discard outgoing messages to legitimate addresses. Congratulations. You're encouraging broken web sites, lost information, failed communications, increased spam, and just plain bad user experiences. I suggest you rethink this, or at least do a decent job of keeping legitimate domains off of your list.

**Comment by danhstevens** [comment]
I use boun.cr to protect my privacy which is much like spamgourmet. I also operate boun.cr. That didn't stop me from adding boun.cr to this list, however, because at the end of the day it's a disposable email domain. 

I realize some people want to protect their privacy with disposable email domains, and perhaps some implementations of this repo are overzealous (which we obviously have no control over). But also keep in mind many people use services like my boun.cr service to abuse other services and website operators have a right to know about such domains and make the decision for themselves as to how to handle them.

**Comment by mintar** [comment]
I 100% support removing all spamgourmet domains from this list, but I have 0% hope that it will ever happen. The devs behind `disposable_email_checker` and `disposable-email-domains` are not on the users' side but on the side of the ~~spammers~~ marketing department. To them, a user's email address is an "asset", and the more control a user has about what emails they receive the less valuable that asset is. That is why email services with easy spam filtering like spamgourmet are blocked - it would be a shame if the user missed all those special offers that the marketing droids are sending them, wouldn't it?

The real problem about this is that as more and more websites use this service, they silently stop sending me emails (although my spamgourmet email has worked for years with that website). Sometimes I can't even change my email address, because that would require me to click a confirmation link that the website never sends because spamgourmet.com is on this block list.

I try my best to email the website devs and alert them to the problem, and to fight the cancer that `disposable_email_checker` and `disposable-email-domains` are, but it feels like tilting at windmills.
