### ISSUE TITLE
Query - Craigslist

### ISSUE THREAD

**Issue by cucx** [ivolo/disposable-email-domains#609]
Hello!

Is there a specific reason why some Craigslist sub domains are added as a disposable domain that i'm overlooking? 
For example:
```
comm.craigslist.org
gigs.craigslist.org
hous.craigslist.org
job.craigslist.org 
pers.craigslist.org
res.craigslist.org 
sale.craigslist.org
serv.craigslist.org
```
Thanks!

**Comment by kavacky** [comment]
My guess they use random generated email addresses with these domains to send messages between users internally (<guid>@sub.craigslist.org, something like that), so they are not legit emails to use anywhere else.

**Comment by danhstevens** [comment]
That's correct. These are by definition disposable since they are generated by craigslist when an ad is placed and only exist for the lifetime of the ad. Craigslist uses them for the noble purpose of preventing the exposure of individual's actual email address which is great - but it's therefore an email address you shouldn't be collecting on your sign up forms, etc.
