### ISSUE TITLE
Remove privaterelay.appleid.com

### ISSUE THREAD

**Issue by Timothylock** [ivolo/disposable-email-domains#704]
`privaterelay.appleid.com` is an email relay service used by Apple in their new Sign In With Apple (iOS13) and any app/site that wants to implement sign in with apple must allow the user to sign up with this relay email. 

Reason why issue is created is because although this could be seen as a disposable email, it is in fact tied to an apple account

**Comment by tompec** [comment]
You're right, I've removed it in my current [PR](https://github.com/ivolo/disposable-email-domains/pull/703).

**Comment by danhstevens** [comment]
I'm open for further discussion but I tend to think `privaterelay.appleid.com` fits the classification of disposable. 

From https://en.wikipedia.org/wiki/Disposable_email_address:
> Disposable email addressing refers to an approach where a unique email address is used for every contact or entity

The fact that it's a relay which ties in to a real email address is fairly common and we'd need to remove perhaps 1/3rd of the providers on this list as they are also relays.

Anything else I'm missing that disqualifies it from being disposable by definition? Developers that want to allow `privaterelay.appleid.com` as a part of their integration with Apple would be free to make a simple exception in their logic to allow it and those that don't have such an integration would be able to know they've been given a disposable email address and can handle it however they prefer.

**Comment by tompec** [comment]
It's a bit of a gray area.
From what I understand, Apple users get a unique alias across all apps written by a single development team, which means they can't create several accounts from the same iCloud account.
Apple guaranties the deliverability and make sure it's tied to a valid iCloud account.
So I personally don't see why I would block those addresses, since it won't affect the deliverability or allow a single person to create more than one account.
More infos: https://developer.apple.com/documentation/signinwithapplejs/communicating_using_the_private_email_relay_service

**Comment by danhstevens** [comment]
Alright sounds good. I'll merge the PR with the removal. If there are community requests to add it we can reconsider. Thanks.
