### ISSUE TITLE
http://www.33mail.com/signup

### ISSUE THREAD

**Issue by MikeMichel** [ivolo/disposable-email-domains#95]
http://www.33mail.com/signup creates mails like alias@USERNAME.33mail.com. It seems the block does not work here. Any chance to get it work?

**Comment by mariomka** [comment]
Adding a wildcard can be an option, example: *.33mail.com

**Comment by tompec** [comment]
@MikeMichel If you need to create an account, it's not a disposable domain.

**Comment by MikeMichel** [comment]
@tompec see http://www.33mail.com/

"UNLIMITED FREE DISPOSABLE EMAIL ADDRESSES"

**Comment by danhstevens** [comment]
I agree that there are a number of domains that are wildcards that we'll need to look towards supporting. I'll think on this a bit and see what the best route is.

**Comment by tompec** [comment]
The best way in my opinion would be to create a separate list for wildcards domains and let the users handle it the way they want. Because we can't just throw a *.domain.com in the current list, it would ruin the logic.

Sorry @MikeMichel, I just saw the signup link and thought it was that kind of website... ☺️

**Comment by danhstevens** [comment]
Agreed. I'll create a `wildcards.json` file for that purpose and we'll leave it up to the users to implement accordingly.

**Comment by danhstevens** [comment]
Fixed via	8ccdaa9

**Comment by Lissy93** [comment]
I know I'm late to this, but 33mail is not used in this context, they have a verified sign up process. It's basically a privacy tool, and since it requires verification in the sign up process, it is rarely used by to create spam accounts. So I don't think it should be on this list. I know many (including myself) who have used this service for years to have different aliases for work and personal emails etc, while having everything land in the same inbox.

So I don't think it seems right to block 33m domains. Would anyone mind if I opened a PR to fix this?

Cheers,
Alicia 🚀
